# Header

menu:
  主页: /
  时光轴: /archives/
  程序开发: /tags/程序/
  诗文随笔: /tags/随笔/
  留言板: /message.html

# SubNav
subnav:
  github: "https://github.com/smarterq"
  weibo: "https://weibo.com/smarterq"
  #rss: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:i@xhtml.love"
  #facebook: "#"
  #google: "#"
  twitter: "https://twitter.com/Julydate"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: '/img/alipay.png'
# 微信二维码图片地址
weixin: '/img/wxpay.png'

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: '/img/favicon.ico'

#你的头像url
avatar: '/img/head.jpg'

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: julydate

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#fe91b4'
  # 右滑板块背景
  slider: 'url(https://www.julydate.com/img/bg.jpg)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于'

friends: 
  xiaopc: https://xiaopc.org/
  近泽jrotty: https://qqdie.com/
  吟梦的梦笔记: https://kirainmoe.com/
  萌月: http://www.moeyue.com/
  空樱酱: https://kotori.love/
  DIYgod: https://diygod.me/
  蠢汤圆: https://tyzual.com/
  立华: https://freedom.moe/
  s7smile: http://www.s7smile.com/
  tea9: https://tea9.xyz
  折影轻梦: https://nexmoe.com/
  诗酒乘年华: https://shawnzeng.com/
  蠢Lan: https://www.xx8.uk/
  咸鱼滩音乐团队: https://www.xytsing.com/
  王煜博客: https://blog.wixy.cn/
  该问: http://www.theask.cn/
  呆头鹅: https://lonelybsh.github.io/
  猫行天下: http://www.aidcat.com/

aboutme: 无关风月<br>不忘初心